# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class TodoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListTask = channel.unary_stream(
        '/todo.Todo/ListTask',
        request_serializer=todo__pb2.ListTaskRequest.SerializeToString,
        response_deserializer=todo__pb2.ListTaskResponse.FromString,
        )
    self.GetTaskById = channel.unary_unary(
        '/todo.Todo/GetTaskById',
        request_serializer=todo__pb2.GetTaskByIdRequest.SerializeToString,
        response_deserializer=todo__pb2.GetTaskByIdResponce.FromString,
        )
    self.GetTaskByName = channel.unary_unary(
        '/todo.Todo/GetTaskByName',
        request_serializer=todo__pb2.GetTaskByNameRequest.SerializeToString,
        response_deserializer=todo__pb2.GetTaskByNameResponce.FromString,
        )


class TodoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListTask(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTaskById(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTaskByName(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListTask': grpc.unary_stream_rpc_method_handler(
          servicer.ListTask,
          request_deserializer=todo__pb2.ListTaskRequest.FromString,
          response_serializer=todo__pb2.ListTaskResponse.SerializeToString,
      ),
      'GetTaskById': grpc.unary_unary_rpc_method_handler(
          servicer.GetTaskById,
          request_deserializer=todo__pb2.GetTaskByIdRequest.FromString,
          response_serializer=todo__pb2.GetTaskByIdResponce.SerializeToString,
      ),
      'GetTaskByName': grpc.unary_unary_rpc_method_handler(
          servicer.GetTaskByName,
          request_deserializer=todo__pb2.GetTaskByNameRequest.FromString,
          response_serializer=todo__pb2.GetTaskByNameResponce.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.Todo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
